framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

            async_sms_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async_sms_notification
                retry_strategy:
                    max_retries: 5
                    multiplier: 2

            async_email_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async_email_notification
                retry_strategy:
                    max_retries: 5
                    multiplier: 2

        routing:
            App\Messenger\Message\SmsNotificationMessage: async_sms_notification
            App\Messenger\Message\EmailNotificationMessage: async_email_notification

            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
