version: '3.5'

services:
  sf_task_db_postgres:
    image: postgres:14-alpine
    container_name: sf_task_db_postgres
    environment:
      POSTGRES_DB: 'sf_task'
      POSTGRES_PASSWORD: 'sf_task'
      POSTGRES_USER: 'sf_task'
    ports:
      - "5432:5432"
    volumes:
      - sf-task-database:/var/lib/postgresql/data:rw

  sf_task_php81:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    image: php81_sf_task_local:latest
    container_name: sf_task_container
    ports:
      - "8085:80"
    volumes:
      - ./.docker/dev/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/var/www:cached
    depends_on:
      - database
    links:
      - database

volumes:
  sf-task-database:
